services:
  nginx-loadbalancer:
    image: nginx:latest
    container_name: nginx-loadbalancer
    volumes:
      - ./config/loadbalancer.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - nginx-node1
      - nginx-node2
      - nginx-node3
      - nginx-node4

  nginx-node1:
    image: nginx:latest
    container_name: nginx-node1
    volumes:
      - ./config/node.conf:/etc/nginx/conf.d/default.conf
      - ./html/node1.html:/usr/share/nginx/html/index.html
    ports:
      - "80"

  nginx-node2:
    image: nginx:latest
    container_name: nginx-node2
    volumes:
      - ./config/node.conf:/etc/nginx/conf.d/default.conf
      - ./html/node2.html:/usr/share/nginx/html/index.html
    ports:
      - "80"

  nginx-node3:
    image: nginx:latest
    container_name: nginx-node3
    volumes:
      - ./config/node.conf:/etc/nginx/conf.d/default.conf
      - ./html/node3.html:/usr/share/nginx/html/index.html
    ports:
      - "80"

  nginx-node4:
    image: nginx:latest
    container_name: nginx-node4
    volumes:
      - ./config/node.conf:/etc/nginx/conf.d/default.conf
      - ./html/node4.html:/usr/share/nginx/html/index.html
    ports:
      - "80"